services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn django_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: SECRET_KEY
        value: django-insecure-=j@pcr&jj5z+xiajx5=+#zs-t^j3)6(dcbp)@yz7z#*amg%$uq
      